### ISSUE TITLE
MoreKB module in Augustus Client

### ISSUE THREAD

**Issue by Ush82** [AugustusClient/Augustus-Wiki#63]
### Modes

- **STap**: Simulates the PvP S-Tap technique by increasing recoil through movement control.
- **LegitSneak**: Implements the Shift-Tap (Sneak-Tap) technique to control and enhance recoil.
- **Legit**: Simulates the PvP technique of W-Tap for legitimate recoil enhancement.
- **LegitFast**: A faster and more aggressive version of Legit for increased recoil.
- **Fast**: Maximizes kickback through high frequency of action.
- **LessPacket**: Reduces the number of packets sent.
- **Packet**: Uses special packets to enhance the payoff.
- **DoublePacket**: Doubles the number of packets to maximize the output.
- **One**: Minimalistic mode for neat recoil control.

## Timing settings

- **MinSprintResetTime / MaxSprintResetTime**: Set the delay in ticks for W-Tap after successfully hitting a target.
- **NotInARow**: Prohibits the use of identical W-Tap delays in a row.
- **MaxInARow**: Maximum number of repetitions in a row.
- **Outliers**: Excludes outliers.
- **MinSprintResetTimeOutlierValue / MaxSprintResetTimeOutlierValue**: Values to handle outliers.
- **MinOutlierDelay / MaxOutlierDelay**: Set the minimum and maximum delay for emissions.
- **Normal Distribution**: Enables uniform distribution of time values.
- **Sigma / Center**: Distribution settings.

## Duration settings

- **MinSprintResetDuration / MaxSprintResetDuration**: Number of ticks for which W-Tap will be active.
- **NotInARow**: Prohibits the same W-Tap duration consecutively.
- **Outliers, Normal Distribution**: Operate similarly to the Timing settings.

## DoubleReset settings

- **DoubleSprintReset**: Enables or disables double W-Tap.
- **MinDoubleResetTiming / MaxDoubleResetTiming**: Delay in ticks for W-Tap after a successful hit on a target.
- **MinDoubleResetDelay / MaxDoubleResetDelay**: Delay between two W-Taps.
- **MinDoubleResetDelayOutlierValue / MaxDoubleResetDelayOutlierValue**: Values for handling outliers.
- **MinOutlierDelay / MaxOutlierDelay**: Minimum and maximum emission delay settings.
- **Normal Distribution**: Enables normal distribution.
- **Sigma / Center**: Distribution settings for double reset.

## Fail Settings

- **FailSprintReset**: Enables or disables random W-Tap misses.
- **MinFailDelay / MaxFailDelay**: Delay in ticks between W-Tap skips.
- **MinFailDuration / MaxFailDuration**: Number of ticks for which the pass will be active.
- **NotInARow**: Prevents identical skips in a row.
- **Normal Distribution**: Configures an even distribution of time values.
- **Sigma / Center**: Distribution parameters for skips.

**Comment by Muffinmaker2** [comment]
Ooooh this one is a good one will add asap :3

**Comment by Ush82** [comment]
maybe you're planning on doing a Russian translation?

# Модуль MoreKB в Augustus Client

## Основные параметры

### Режимы

- **STap**: Имитирует технику PvP S-Tap, увеличивая отдачу через управление движением.
- **LegitSneak**: Реализует технику Shift-Tap (Sneak-Tap) для контроля и усиления отдачи.
- **Legit**: Симулирует PvP технику W-Tap для легитимного увеличения отдачи.
- **LegitFast**: Более быстрая и агрессивная версия Legit, позволяющая усилить отдачу.
- **Fast**: Максимизирует отдачу за счёт высокой частоты действий.
- **LessPacket**: Уменьшает количество отправляемых пакетов.
- **Packet**: Использует специальные пакеты для усиления отдачи.
- **DoublePacket**: Удваивает количество пакетов для максимальной отдачи.
- **One**: Минималистичный режим для аккуратного управления отдачей.

## Настройки Timing

- **MinSprintResetTime / MaxSprintResetTime**: Устанавливают задержку в тиках для W-Tap после успешного попадания по цели.
- **NotInARow**: Запрещает использование одинаковых задержек W-Tap подряд.
- **MaxInARow**: Максимальное количество повторений подряд.
- **Outliers**: Исключает выбросы.
- **MinSprintResetTimeOutlierValue / MaxSprintResetTimeOutlierValue**: Значения для обработки выбросов.
- **MinOutlierDelay / MaxOutlierDelay**: Устанавливают минимальную и максимальную задержку для выбросов.
- **Normal Distribution**: Включает равномерное распределение значений времени.
- **Sigma / Center**: Параметры распределения.

## Настройки Duration

- **MinSprintResetDuration / MaxSprintResetDuration**: Количество тиков, в течение которых будет активен W-Tap.
- **NotInARow**: Запрещает одинаковую продолжительность W-Tap подряд.
- **Outliers, Normal Distribution**: Работают аналогично параметрам Timing.

## Настройки DoubleReset

- **DoubleSprintReset**: Включает или отключает двойной W-Tap.
- **MinDoubleResetTiming / MaxDoubleResetTiming**: Задержка в тиках для W-Tap после успешного попадания по цели.
- **MinDoubleResetDelay / MaxDoubleResetDelay**: Задержка между двумя W-Tap.
- **MinDoubleResetDelayOutlierValue / MaxDoubleResetDelayOutlierValue**: Значения для обработки выбросов.
- **MinOutlierDelay / MaxOutlierDelay**: Настройки минимальной и максимальной задержки выбросов.
- **Normal Distribution**: Включает равномерное распределение.
- **Sigma / Center**: Параметры распределения для двойного сброса.

## Настройки Fail

- **FailSprintReset**: Включает или отключает случайные пропуски W-Tap.
- **MinFailDelay / MaxFailDelay**: Задержка в тиках между пропусками W-Tap.
- **MinFailDuration / MaxFailDuration**: Количество тиков, в течение которых будет активен пропуск.
- **NotInARow**: Предотвращает одинаковые пропуски подряд.
- **Normal Distribution**: Настраивает равномерное распределение значений времени.
- **Sigma / Center**: Параметры распределения для пропусков.

**Comment by Muffinmaker2** [comment]
Has been added, will be merged at the end of the day. Thanks :D
