### ISSUE TITLE
Anticheat

### ISSUE THREAD

**Issue by lemons5616** [AugustusClient/Augustus-Wiki#64]
### Wrong Anticheats

"Intave is used by servers like MCCentral / Herobrine.org / universocraft / Gamster."

Universocraft uses Polar.
Gamster uses Polar.
Herobrine.org uses Grim.
MCCentral: Idk but its not Intave

**Comment by Muffinmaker2** [comment]
Very nice very good will add asap :D

**Comment by Muffinmaker2** [comment]
Is now fixed and will be pushed at the end of the day. Thanks <3
