### ISSUE TITLE
just if you need it idk

### ISSUE THREAD

**Issue by lemons5616** [AugustusClient/Augustus-Wiki#65]
### What is the Addition?

Polar:
Hycraft
Universocraft
Gamster
Craftok

Grim:
Zentic
Zonecraft (I think custom fork)
Herobrine
Hylex

Sorry if too many suggestion

**Comment by Muffinmaker2** [comment]
Very nice :D will merge with a diffrent issue in a min

**Comment by Muffinmaker2** [comment]
Is now implemented. Will be merged at end of day. Thank you :3
