### ISSUE TITLE
Wrong Description

### ISSUE THREAD

**Issue by lemons5616** [AugustusClient/Augustus-Wiki#66]
### What is the Correction?

https://augustusclient.github.io/Augustus-Wiki/render/blockanimation/#none

Block animation desc is:
"Replaces all barriers with a broken texture pack to make them visible"

https://augustusclient.github.io/Augustus-Wiki/render/notification/
add the new notification mode?

**Comment by Muffinmaker2** [comment]
Have fixed it and the new notification stuffw will be added later :) Thanks
